package com.ssm.kernel.model;

public class CaseWithBLOBs extends Case {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.handle_user_ids
     *
     * @mbg.generated
     */
    private String handleUserIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.handle_user_names
     *
     * @mbg.generated
     */
    private String handleUserNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.handle_user_ids
     *
     * @return the value of case.handle_user_ids
     *
     * @mbg.generated
     */
    public String getHandleUserIds() {
        return handleUserIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.handle_user_ids
     *
     * @param handleUserIds the value for case.handle_user_ids
     *
     * @mbg.generated
     */
    public void setHandleUserIds(String handleUserIds) {
        this.handleUserIds = handleUserIds == null ? null : handleUserIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.handle_user_names
     *
     * @return the value of case.handle_user_names
     *
     * @mbg.generated
     */
    public String getHandleUserNames() {
        return handleUserNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.handle_user_names
     *
     * @param handleUserNames the value for case.handle_user_names
     *
     * @mbg.generated
     */
    public void setHandleUserNames(String handleUserNames) {
        this.handleUserNames = handleUserNames == null ? null : handleUserNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.description
     *
     * @return the value of case.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.description
     *
     * @param description the value for case.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}