package com.ssm.kernel.model;

import java.util.Date;

public class Case {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.case_no
     *
     * @mbg.generated
     */
    private String caseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.case_name
     *
     * @mbg.generated
     */
    private String caseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.case_type_id
     *
     * @mbg.generated
     */
    private Integer caseTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.case_type_id_2
     *
     * @mbg.generated
     */
    private Integer caseTypeId2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.case_status
     *
     * @mbg.generated
     */
    private String caseStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.address_name
     *
     * @mbg.generated
     */
    private String addressName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.address_longitude
     *
     * @mbg.generated
     */
    private Float addressLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.address_latitude
     *
     * @mbg.generated
     */
    private Float addressLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.modus_operandi
     *
     * @mbg.generated
     */
    private String modusOperandi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.suspect_num
     *
     * @mbg.generated
     */
    private Integer suspectNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.area_id
     *
     * @mbg.generated
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.handle_department_id
     *
     * @mbg.generated
     */
    private Integer handleDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.register_time
     *
     * @mbg.generated
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.report_time
     *
     * @mbg.generated
     */
    private Date reportTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.report_person
     *
     * @mbg.generated
     */
    private String reportPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.report_phone
     *
     * @mbg.generated
     */
    private String reportPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.area_department_id
     *
     * @mbg.generated
     */
    private Integer areaDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.illegal_person_exist
     *
     * @mbg.generated
     */
    private String illegalPersonExist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.victim_person_exists
     *
     * @mbg.generated
     */
    private String victimPersonExists;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.break_time
     *
     * @mbg.generated
     */
    private Date breakTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.withdraw_time
     *
     * @mbg.generated
     */
    private Date withdrawTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.find_time
     *
     * @mbg.generated
     */
    private Date findTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.find_address_name
     *
     * @mbg.generated
     */
    private String findAddressName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.find_address_description
     *
     * @mbg.generated
     */
    private String findAddressDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.create_department_id
     *
     * @mbg.generated
     */
    private Integer createDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.create_user_id
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.create_user_name
     *
     * @mbg.generated
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.update_user_id
     *
     * @mbg.generated
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.update_user_name
     *
     * @mbg.generated
     */
    private String updateUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.id
     *
     * @return the value of case.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.id
     *
     * @param id the value for case.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.case_no
     *
     * @return the value of case.case_no
     *
     * @mbg.generated
     */
    public String getCaseNo() {
        return caseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.case_no
     *
     * @param caseNo the value for case.case_no
     *
     * @mbg.generated
     */
    public void setCaseNo(String caseNo) {
        this.caseNo = caseNo == null ? null : caseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.case_name
     *
     * @return the value of case.case_name
     *
     * @mbg.generated
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.case_name
     *
     * @param caseName the value for case.case_name
     *
     * @mbg.generated
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName == null ? null : caseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.case_type_id
     *
     * @return the value of case.case_type_id
     *
     * @mbg.generated
     */
    public Integer getCaseTypeId() {
        return caseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.case_type_id
     *
     * @param caseTypeId the value for case.case_type_id
     *
     * @mbg.generated
     */
    public void setCaseTypeId(Integer caseTypeId) {
        this.caseTypeId = caseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.case_type_id_2
     *
     * @return the value of case.case_type_id_2
     *
     * @mbg.generated
     */
    public Integer getCaseTypeId2() {
        return caseTypeId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.case_type_id_2
     *
     * @param caseTypeId2 the value for case.case_type_id_2
     *
     * @mbg.generated
     */
    public void setCaseTypeId2(Integer caseTypeId2) {
        this.caseTypeId2 = caseTypeId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.case_status
     *
     * @return the value of case.case_status
     *
     * @mbg.generated
     */
    public String getCaseStatus() {
        return caseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.case_status
     *
     * @param caseStatus the value for case.case_status
     *
     * @mbg.generated
     */
    public void setCaseStatus(String caseStatus) {
        this.caseStatus = caseStatus == null ? null : caseStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.start_time
     *
     * @return the value of case.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.start_time
     *
     * @param startTime the value for case.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.end_time
     *
     * @return the value of case.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.end_time
     *
     * @param endTime the value for case.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.address_name
     *
     * @return the value of case.address_name
     *
     * @mbg.generated
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.address_name
     *
     * @param addressName the value for case.address_name
     *
     * @mbg.generated
     */
    public void setAddressName(String addressName) {
        this.addressName = addressName == null ? null : addressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.address_longitude
     *
     * @return the value of case.address_longitude
     *
     * @mbg.generated
     */
    public Float getAddressLongitude() {
        return addressLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.address_longitude
     *
     * @param addressLongitude the value for case.address_longitude
     *
     * @mbg.generated
     */
    public void setAddressLongitude(Float addressLongitude) {
        this.addressLongitude = addressLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.address_latitude
     *
     * @return the value of case.address_latitude
     *
     * @mbg.generated
     */
    public Float getAddressLatitude() {
        return addressLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.address_latitude
     *
     * @param addressLatitude the value for case.address_latitude
     *
     * @mbg.generated
     */
    public void setAddressLatitude(Float addressLatitude) {
        this.addressLatitude = addressLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.modus_operandi
     *
     * @return the value of case.modus_operandi
     *
     * @mbg.generated
     */
    public String getModusOperandi() {
        return modusOperandi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.modus_operandi
     *
     * @param modusOperandi the value for case.modus_operandi
     *
     * @mbg.generated
     */
    public void setModusOperandi(String modusOperandi) {
        this.modusOperandi = modusOperandi == null ? null : modusOperandi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.suspect_num
     *
     * @return the value of case.suspect_num
     *
     * @mbg.generated
     */
    public Integer getSuspectNum() {
        return suspectNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.suspect_num
     *
     * @param suspectNum the value for case.suspect_num
     *
     * @mbg.generated
     */
    public void setSuspectNum(Integer suspectNum) {
        this.suspectNum = suspectNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.area_id
     *
     * @return the value of case.area_id
     *
     * @mbg.generated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.area_id
     *
     * @param areaId the value for case.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.handle_department_id
     *
     * @return the value of case.handle_department_id
     *
     * @mbg.generated
     */
    public Integer getHandleDepartmentId() {
        return handleDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.handle_department_id
     *
     * @param handleDepartmentId the value for case.handle_department_id
     *
     * @mbg.generated
     */
    public void setHandleDepartmentId(Integer handleDepartmentId) {
        this.handleDepartmentId = handleDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.register_time
     *
     * @return the value of case.register_time
     *
     * @mbg.generated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.register_time
     *
     * @param registerTime the value for case.register_time
     *
     * @mbg.generated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.report_time
     *
     * @return the value of case.report_time
     *
     * @mbg.generated
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.report_time
     *
     * @param reportTime the value for case.report_time
     *
     * @mbg.generated
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.report_person
     *
     * @return the value of case.report_person
     *
     * @mbg.generated
     */
    public String getReportPerson() {
        return reportPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.report_person
     *
     * @param reportPerson the value for case.report_person
     *
     * @mbg.generated
     */
    public void setReportPerson(String reportPerson) {
        this.reportPerson = reportPerson == null ? null : reportPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.report_phone
     *
     * @return the value of case.report_phone
     *
     * @mbg.generated
     */
    public String getReportPhone() {
        return reportPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.report_phone
     *
     * @param reportPhone the value for case.report_phone
     *
     * @mbg.generated
     */
    public void setReportPhone(String reportPhone) {
        this.reportPhone = reportPhone == null ? null : reportPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.area_department_id
     *
     * @return the value of case.area_department_id
     *
     * @mbg.generated
     */
    public Integer getAreaDepartmentId() {
        return areaDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.area_department_id
     *
     * @param areaDepartmentId the value for case.area_department_id
     *
     * @mbg.generated
     */
    public void setAreaDepartmentId(Integer areaDepartmentId) {
        this.areaDepartmentId = areaDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.illegal_person_exist
     *
     * @return the value of case.illegal_person_exist
     *
     * @mbg.generated
     */
    public String getIllegalPersonExist() {
        return illegalPersonExist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.illegal_person_exist
     *
     * @param illegalPersonExist the value for case.illegal_person_exist
     *
     * @mbg.generated
     */
    public void setIllegalPersonExist(String illegalPersonExist) {
        this.illegalPersonExist = illegalPersonExist == null ? null : illegalPersonExist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.victim_person_exists
     *
     * @return the value of case.victim_person_exists
     *
     * @mbg.generated
     */
    public String getVictimPersonExists() {
        return victimPersonExists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.victim_person_exists
     *
     * @param victimPersonExists the value for case.victim_person_exists
     *
     * @mbg.generated
     */
    public void setVictimPersonExists(String victimPersonExists) {
        this.victimPersonExists = victimPersonExists == null ? null : victimPersonExists.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.break_time
     *
     * @return the value of case.break_time
     *
     * @mbg.generated
     */
    public Date getBreakTime() {
        return breakTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.break_time
     *
     * @param breakTime the value for case.break_time
     *
     * @mbg.generated
     */
    public void setBreakTime(Date breakTime) {
        this.breakTime = breakTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.withdraw_time
     *
     * @return the value of case.withdraw_time
     *
     * @mbg.generated
     */
    public Date getWithdrawTime() {
        return withdrawTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.withdraw_time
     *
     * @param withdrawTime the value for case.withdraw_time
     *
     * @mbg.generated
     */
    public void setWithdrawTime(Date withdrawTime) {
        this.withdrawTime = withdrawTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.find_time
     *
     * @return the value of case.find_time
     *
     * @mbg.generated
     */
    public Date getFindTime() {
        return findTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.find_time
     *
     * @param findTime the value for case.find_time
     *
     * @mbg.generated
     */
    public void setFindTime(Date findTime) {
        this.findTime = findTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.find_address_name
     *
     * @return the value of case.find_address_name
     *
     * @mbg.generated
     */
    public String getFindAddressName() {
        return findAddressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.find_address_name
     *
     * @param findAddressName the value for case.find_address_name
     *
     * @mbg.generated
     */
    public void setFindAddressName(String findAddressName) {
        this.findAddressName = findAddressName == null ? null : findAddressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.find_address_description
     *
     * @return the value of case.find_address_description
     *
     * @mbg.generated
     */
    public String getFindAddressDescription() {
        return findAddressDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.find_address_description
     *
     * @param findAddressDescription the value for case.find_address_description
     *
     * @mbg.generated
     */
    public void setFindAddressDescription(String findAddressDescription) {
        this.findAddressDescription = findAddressDescription == null ? null : findAddressDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.create_department_id
     *
     * @return the value of case.create_department_id
     *
     * @mbg.generated
     */
    public Integer getCreateDepartmentId() {
        return createDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.create_department_id
     *
     * @param createDepartmentId the value for case.create_department_id
     *
     * @mbg.generated
     */
    public void setCreateDepartmentId(Integer createDepartmentId) {
        this.createDepartmentId = createDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.create_user_id
     *
     * @return the value of case.create_user_id
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.create_user_id
     *
     * @param createUserId the value for case.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.create_user_name
     *
     * @return the value of case.create_user_name
     *
     * @mbg.generated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.create_user_name
     *
     * @param createUserName the value for case.create_user_name
     *
     * @mbg.generated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.create_time
     *
     * @return the value of case.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.create_time
     *
     * @param createTime the value for case.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.update_user_id
     *
     * @return the value of case.update_user_id
     *
     * @mbg.generated
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.update_user_id
     *
     * @param updateUserId the value for case.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.update_user_name
     *
     * @return the value of case.update_user_name
     *
     * @mbg.generated
     */
    public String getUpdateUserName() {
        return updateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.update_user_name
     *
     * @param updateUserName the value for case.update_user_name
     *
     * @mbg.generated
     */
    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName == null ? null : updateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.update_time
     *
     * @return the value of case.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.update_time
     *
     * @param updateTime the value for case.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}