package com.ssm.kernel.model;

import java.util.Date;

public class CaseType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.case_type_no
     *
     * @mbg.generated
     */
    private String caseTypeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.case_type_name
     *
     * @mbg.generated
     */
    private String caseTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.create_user_id
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.create_user_name
     *
     * @mbg.generated
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.update_user_id
     *
     * @mbg.generated
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.update_user_name
     *
     * @mbg.generated
     */
    private String updateUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_type.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.id
     *
     * @return the value of case_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.id
     *
     * @param id the value for case_type.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.case_type_no
     *
     * @return the value of case_type.case_type_no
     *
     * @mbg.generated
     */
    public String getCaseTypeNo() {
        return caseTypeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.case_type_no
     *
     * @param caseTypeNo the value for case_type.case_type_no
     *
     * @mbg.generated
     */
    public void setCaseTypeNo(String caseTypeNo) {
        this.caseTypeNo = caseTypeNo == null ? null : caseTypeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.case_type_name
     *
     * @return the value of case_type.case_type_name
     *
     * @mbg.generated
     */
    public String getCaseTypeName() {
        return caseTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.case_type_name
     *
     * @param caseTypeName the value for case_type.case_type_name
     *
     * @mbg.generated
     */
    public void setCaseTypeName(String caseTypeName) {
        this.caseTypeName = caseTypeName == null ? null : caseTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.parent_id
     *
     * @return the value of case_type.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.parent_id
     *
     * @param parentId the value for case_type.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.description
     *
     * @return the value of case_type.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.description
     *
     * @param description the value for case_type.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.create_user_id
     *
     * @return the value of case_type.create_user_id
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.create_user_id
     *
     * @param createUserId the value for case_type.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.create_user_name
     *
     * @return the value of case_type.create_user_name
     *
     * @mbg.generated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.create_user_name
     *
     * @param createUserName the value for case_type.create_user_name
     *
     * @mbg.generated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.create_time
     *
     * @return the value of case_type.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.create_time
     *
     * @param createTime the value for case_type.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.update_user_id
     *
     * @return the value of case_type.update_user_id
     *
     * @mbg.generated
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.update_user_id
     *
     * @param updateUserId the value for case_type.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.update_user_name
     *
     * @return the value of case_type.update_user_name
     *
     * @mbg.generated
     */
    public String getUpdateUserName() {
        return updateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.update_user_name
     *
     * @param updateUserName the value for case_type.update_user_name
     *
     * @mbg.generated
     */
    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName == null ? null : updateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_type.update_time
     *
     * @return the value of case_type.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_type.update_time
     *
     * @param updateTime the value for case_type.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}