package com.ssm.kernel.model;

import java.util.Date;

public class YLMCaseInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CaseNo
     *
     * @mbg.generated
     */
    private String caseno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CaseName
     *
     * @mbg.generated
     */
    private String casename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.RegisterTime
     *
     * @mbg.generated
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.ReportTime
     *
     * @mbg.generated
     */
    private Date reporttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.BreakTime
     *
     * @mbg.generated
     */
    private Date breaktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.WithdrawTime
     *
     * @mbg.generated
     */
    private Date withdrawtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.FindTime
     *
     * @mbg.generated
     */
    private Date findtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.FindAddressName
     *
     * @mbg.generated
     */
    private String findaddressname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CaseTypeID
     *
     * @mbg.generated
     */
    private Integer casetypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CaseLevel
     *
     * @mbg.generated
     */
    private Integer caselevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.StartTime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.EndTime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.AddressName
     *
     * @mbg.generated
     */
    private String addressname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.AddressLogitude
     *
     * @mbg.generated
     */
    private Float addresslogitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.AddressLatitude
     *
     * @mbg.generated
     */
    private Float addresslatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.IsRegister
     *
     * @mbg.generated
     */
    private String isregister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.Property
     *
     * @mbg.generated
     */
    private String property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CaseStatus
     *
     * @mbg.generated
     */
    private String casestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.Description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.SuspectNumber
     *
     * @mbg.generated
     */
    private Integer suspectnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.HandleOfficeID
     *
     * @mbg.generated
     */
    private Integer handleofficeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.HandleUsers
     *
     * @mbg.generated
     */
    private String handleusers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.ReportPerson
     *
     * @mbg.generated
     */
    private String reportperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.ReportPhone
     *
     * @mbg.generated
     */
    private String reportphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.AreaOffice
     *
     * @mbg.generated
     */
    private String areaoffice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.IllegalPersonExists
     *
     * @mbg.generated
     */
    private String illegalpersonexists;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CreateOfficeID
     *
     * @mbg.generated
     */
    private String createofficeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.IsMurderCase
     *
     * @mbg.generated
     */
    private String ismurdercase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.SiteSurveyNo
     *
     * @mbg.generated
     */
    private String sitesurveyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.HandleCaseNo
     *
     * @mbg.generated
     */
    private String handlecaseno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.PoliceComprehensiveNo
     *
     * @mbg.generated
     */
    private String policecomprehensiveno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.SceneInquestNo
     *
     * @mbg.generated
     */
    private String sceneinquestno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.ReceivingAlarmNo
     *
     * @mbg.generated
     */
    private String receivingalarmno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.IntelligenceCaseNo
     *
     * @mbg.generated
     */
    private String intelligencecaseno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.SuffererName
     *
     * @mbg.generated
     */
    private String sufferername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.SuffererGender
     *
     * @mbg.generated
     */
    private String sufferergender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.SuffererInfo
     *
     * @mbg.generated
     */
    private String suffererinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CrimeOpportunity
     *
     * @mbg.generated
     */
    private String crimeopportunity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CrimeImporExport
     *
     * @mbg.generated
     */
    private String crimeimporexport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CrimeFeature
     *
     * @mbg.generated
     */
    private String crimefeature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CrimeTools
     *
     * @mbg.generated
     */
    private String crimetools;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CrimeImplement
     *
     * @mbg.generated
     */
    private String crimeimplement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.SelectionPlace
     *
     * @mbg.generated
     */
    private String selectionplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CrimeMotive
     *
     * @mbg.generated
     */
    private String crimemotive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CaseKeywords
     *
     * @mbg.generated
     */
    private String casekeywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.LossPossession
     *
     * @mbg.generated
     */
    private String losspossession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.InvestigationDesc
     *
     * @mbg.generated
     */
    private String investigationdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yl_m_caseinfo.CaseDownloadNumber
     *
     * @mbg.generated
     */
    private Integer casedownloadnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.ID
     *
     * @return the value of yl_m_caseinfo.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.ID
     *
     * @param id the value for yl_m_caseinfo.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CaseNo
     *
     * @return the value of yl_m_caseinfo.CaseNo
     *
     * @mbg.generated
     */
    public String getCaseno() {
        return caseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CaseNo
     *
     * @param caseno the value for yl_m_caseinfo.CaseNo
     *
     * @mbg.generated
     */
    public void setCaseno(String caseno) {
        this.caseno = caseno == null ? null : caseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CaseName
     *
     * @return the value of yl_m_caseinfo.CaseName
     *
     * @mbg.generated
     */
    public String getCasename() {
        return casename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CaseName
     *
     * @param casename the value for yl_m_caseinfo.CaseName
     *
     * @mbg.generated
     */
    public void setCasename(String casename) {
        this.casename = casename == null ? null : casename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.RegisterTime
     *
     * @return the value of yl_m_caseinfo.RegisterTime
     *
     * @mbg.generated
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.RegisterTime
     *
     * @param registertime the value for yl_m_caseinfo.RegisterTime
     *
     * @mbg.generated
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.ReportTime
     *
     * @return the value of yl_m_caseinfo.ReportTime
     *
     * @mbg.generated
     */
    public Date getReporttime() {
        return reporttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.ReportTime
     *
     * @param reporttime the value for yl_m_caseinfo.ReportTime
     *
     * @mbg.generated
     */
    public void setReporttime(Date reporttime) {
        this.reporttime = reporttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.BreakTime
     *
     * @return the value of yl_m_caseinfo.BreakTime
     *
     * @mbg.generated
     */
    public Date getBreaktime() {
        return breaktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.BreakTime
     *
     * @param breaktime the value for yl_m_caseinfo.BreakTime
     *
     * @mbg.generated
     */
    public void setBreaktime(Date breaktime) {
        this.breaktime = breaktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.WithdrawTime
     *
     * @return the value of yl_m_caseinfo.WithdrawTime
     *
     * @mbg.generated
     */
    public Date getWithdrawtime() {
        return withdrawtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.WithdrawTime
     *
     * @param withdrawtime the value for yl_m_caseinfo.WithdrawTime
     *
     * @mbg.generated
     */
    public void setWithdrawtime(Date withdrawtime) {
        this.withdrawtime = withdrawtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.FindTime
     *
     * @return the value of yl_m_caseinfo.FindTime
     *
     * @mbg.generated
     */
    public Date getFindtime() {
        return findtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.FindTime
     *
     * @param findtime the value for yl_m_caseinfo.FindTime
     *
     * @mbg.generated
     */
    public void setFindtime(Date findtime) {
        this.findtime = findtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.FindAddressName
     *
     * @return the value of yl_m_caseinfo.FindAddressName
     *
     * @mbg.generated
     */
    public String getFindaddressname() {
        return findaddressname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.FindAddressName
     *
     * @param findaddressname the value for yl_m_caseinfo.FindAddressName
     *
     * @mbg.generated
     */
    public void setFindaddressname(String findaddressname) {
        this.findaddressname = findaddressname == null ? null : findaddressname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CaseTypeID
     *
     * @return the value of yl_m_caseinfo.CaseTypeID
     *
     * @mbg.generated
     */
    public Integer getCasetypeid() {
        return casetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CaseTypeID
     *
     * @param casetypeid the value for yl_m_caseinfo.CaseTypeID
     *
     * @mbg.generated
     */
    public void setCasetypeid(Integer casetypeid) {
        this.casetypeid = casetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CaseLevel
     *
     * @return the value of yl_m_caseinfo.CaseLevel
     *
     * @mbg.generated
     */
    public Integer getCaselevel() {
        return caselevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CaseLevel
     *
     * @param caselevel the value for yl_m_caseinfo.CaseLevel
     *
     * @mbg.generated
     */
    public void setCaselevel(Integer caselevel) {
        this.caselevel = caselevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.StartTime
     *
     * @return the value of yl_m_caseinfo.StartTime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.StartTime
     *
     * @param starttime the value for yl_m_caseinfo.StartTime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.EndTime
     *
     * @return the value of yl_m_caseinfo.EndTime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.EndTime
     *
     * @param endtime the value for yl_m_caseinfo.EndTime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.AddressName
     *
     * @return the value of yl_m_caseinfo.AddressName
     *
     * @mbg.generated
     */
    public String getAddressname() {
        return addressname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.AddressName
     *
     * @param addressname the value for yl_m_caseinfo.AddressName
     *
     * @mbg.generated
     */
    public void setAddressname(String addressname) {
        this.addressname = addressname == null ? null : addressname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.AddressLogitude
     *
     * @return the value of yl_m_caseinfo.AddressLogitude
     *
     * @mbg.generated
     */
    public Float getAddresslogitude() {
        return addresslogitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.AddressLogitude
     *
     * @param addresslogitude the value for yl_m_caseinfo.AddressLogitude
     *
     * @mbg.generated
     */
    public void setAddresslogitude(Float addresslogitude) {
        this.addresslogitude = addresslogitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.AddressLatitude
     *
     * @return the value of yl_m_caseinfo.AddressLatitude
     *
     * @mbg.generated
     */
    public Float getAddresslatitude() {
        return addresslatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.AddressLatitude
     *
     * @param addresslatitude the value for yl_m_caseinfo.AddressLatitude
     *
     * @mbg.generated
     */
    public void setAddresslatitude(Float addresslatitude) {
        this.addresslatitude = addresslatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.IsRegister
     *
     * @return the value of yl_m_caseinfo.IsRegister
     *
     * @mbg.generated
     */
    public String getIsregister() {
        return isregister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.IsRegister
     *
     * @param isregister the value for yl_m_caseinfo.IsRegister
     *
     * @mbg.generated
     */
    public void setIsregister(String isregister) {
        this.isregister = isregister == null ? null : isregister.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.Property
     *
     * @return the value of yl_m_caseinfo.Property
     *
     * @mbg.generated
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.Property
     *
     * @param property the value for yl_m_caseinfo.Property
     *
     * @mbg.generated
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CaseStatus
     *
     * @return the value of yl_m_caseinfo.CaseStatus
     *
     * @mbg.generated
     */
    public String getCasestatus() {
        return casestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CaseStatus
     *
     * @param casestatus the value for yl_m_caseinfo.CaseStatus
     *
     * @mbg.generated
     */
    public void setCasestatus(String casestatus) {
        this.casestatus = casestatus == null ? null : casestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.Description
     *
     * @return the value of yl_m_caseinfo.Description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.Description
     *
     * @param description the value for yl_m_caseinfo.Description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.SuspectNumber
     *
     * @return the value of yl_m_caseinfo.SuspectNumber
     *
     * @mbg.generated
     */
    public Integer getSuspectnumber() {
        return suspectnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.SuspectNumber
     *
     * @param suspectnumber the value for yl_m_caseinfo.SuspectNumber
     *
     * @mbg.generated
     */
    public void setSuspectnumber(Integer suspectnumber) {
        this.suspectnumber = suspectnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.HandleOfficeID
     *
     * @return the value of yl_m_caseinfo.HandleOfficeID
     *
     * @mbg.generated
     */
    public Integer getHandleofficeid() {
        return handleofficeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.HandleOfficeID
     *
     * @param handleofficeid the value for yl_m_caseinfo.HandleOfficeID
     *
     * @mbg.generated
     */
    public void setHandleofficeid(Integer handleofficeid) {
        this.handleofficeid = handleofficeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.HandleUsers
     *
     * @return the value of yl_m_caseinfo.HandleUsers
     *
     * @mbg.generated
     */
    public String getHandleusers() {
        return handleusers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.HandleUsers
     *
     * @param handleusers the value for yl_m_caseinfo.HandleUsers
     *
     * @mbg.generated
     */
    public void setHandleusers(String handleusers) {
        this.handleusers = handleusers == null ? null : handleusers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.ReportPerson
     *
     * @return the value of yl_m_caseinfo.ReportPerson
     *
     * @mbg.generated
     */
    public String getReportperson() {
        return reportperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.ReportPerson
     *
     * @param reportperson the value for yl_m_caseinfo.ReportPerson
     *
     * @mbg.generated
     */
    public void setReportperson(String reportperson) {
        this.reportperson = reportperson == null ? null : reportperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.ReportPhone
     *
     * @return the value of yl_m_caseinfo.ReportPhone
     *
     * @mbg.generated
     */
    public String getReportphone() {
        return reportphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.ReportPhone
     *
     * @param reportphone the value for yl_m_caseinfo.ReportPhone
     *
     * @mbg.generated
     */
    public void setReportphone(String reportphone) {
        this.reportphone = reportphone == null ? null : reportphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.AreaOffice
     *
     * @return the value of yl_m_caseinfo.AreaOffice
     *
     * @mbg.generated
     */
    public String getAreaoffice() {
        return areaoffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.AreaOffice
     *
     * @param areaoffice the value for yl_m_caseinfo.AreaOffice
     *
     * @mbg.generated
     */
    public void setAreaoffice(String areaoffice) {
        this.areaoffice = areaoffice == null ? null : areaoffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.IllegalPersonExists
     *
     * @return the value of yl_m_caseinfo.IllegalPersonExists
     *
     * @mbg.generated
     */
    public String getIllegalpersonexists() {
        return illegalpersonexists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.IllegalPersonExists
     *
     * @param illegalpersonexists the value for yl_m_caseinfo.IllegalPersonExists
     *
     * @mbg.generated
     */
    public void setIllegalpersonexists(String illegalpersonexists) {
        this.illegalpersonexists = illegalpersonexists == null ? null : illegalpersonexists.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CreateOfficeID
     *
     * @return the value of yl_m_caseinfo.CreateOfficeID
     *
     * @mbg.generated
     */
    public String getCreateofficeid() {
        return createofficeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CreateOfficeID
     *
     * @param createofficeid the value for yl_m_caseinfo.CreateOfficeID
     *
     * @mbg.generated
     */
    public void setCreateofficeid(String createofficeid) {
        this.createofficeid = createofficeid == null ? null : createofficeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.IsMurderCase
     *
     * @return the value of yl_m_caseinfo.IsMurderCase
     *
     * @mbg.generated
     */
    public String getIsmurdercase() {
        return ismurdercase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.IsMurderCase
     *
     * @param ismurdercase the value for yl_m_caseinfo.IsMurderCase
     *
     * @mbg.generated
     */
    public void setIsmurdercase(String ismurdercase) {
        this.ismurdercase = ismurdercase == null ? null : ismurdercase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.SiteSurveyNo
     *
     * @return the value of yl_m_caseinfo.SiteSurveyNo
     *
     * @mbg.generated
     */
    public String getSitesurveyno() {
        return sitesurveyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.SiteSurveyNo
     *
     * @param sitesurveyno the value for yl_m_caseinfo.SiteSurveyNo
     *
     * @mbg.generated
     */
    public void setSitesurveyno(String sitesurveyno) {
        this.sitesurveyno = sitesurveyno == null ? null : sitesurveyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.HandleCaseNo
     *
     * @return the value of yl_m_caseinfo.HandleCaseNo
     *
     * @mbg.generated
     */
    public String getHandlecaseno() {
        return handlecaseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.HandleCaseNo
     *
     * @param handlecaseno the value for yl_m_caseinfo.HandleCaseNo
     *
     * @mbg.generated
     */
    public void setHandlecaseno(String handlecaseno) {
        this.handlecaseno = handlecaseno == null ? null : handlecaseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.PoliceComprehensiveNo
     *
     * @return the value of yl_m_caseinfo.PoliceComprehensiveNo
     *
     * @mbg.generated
     */
    public String getPolicecomprehensiveno() {
        return policecomprehensiveno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.PoliceComprehensiveNo
     *
     * @param policecomprehensiveno the value for yl_m_caseinfo.PoliceComprehensiveNo
     *
     * @mbg.generated
     */
    public void setPolicecomprehensiveno(String policecomprehensiveno) {
        this.policecomprehensiveno = policecomprehensiveno == null ? null : policecomprehensiveno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.SceneInquestNo
     *
     * @return the value of yl_m_caseinfo.SceneInquestNo
     *
     * @mbg.generated
     */
    public String getSceneinquestno() {
        return sceneinquestno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.SceneInquestNo
     *
     * @param sceneinquestno the value for yl_m_caseinfo.SceneInquestNo
     *
     * @mbg.generated
     */
    public void setSceneinquestno(String sceneinquestno) {
        this.sceneinquestno = sceneinquestno == null ? null : sceneinquestno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.ReceivingAlarmNo
     *
     * @return the value of yl_m_caseinfo.ReceivingAlarmNo
     *
     * @mbg.generated
     */
    public String getReceivingalarmno() {
        return receivingalarmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.ReceivingAlarmNo
     *
     * @param receivingalarmno the value for yl_m_caseinfo.ReceivingAlarmNo
     *
     * @mbg.generated
     */
    public void setReceivingalarmno(String receivingalarmno) {
        this.receivingalarmno = receivingalarmno == null ? null : receivingalarmno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.IntelligenceCaseNo
     *
     * @return the value of yl_m_caseinfo.IntelligenceCaseNo
     *
     * @mbg.generated
     */
    public String getIntelligencecaseno() {
        return intelligencecaseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.IntelligenceCaseNo
     *
     * @param intelligencecaseno the value for yl_m_caseinfo.IntelligenceCaseNo
     *
     * @mbg.generated
     */
    public void setIntelligencecaseno(String intelligencecaseno) {
        this.intelligencecaseno = intelligencecaseno == null ? null : intelligencecaseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.SuffererName
     *
     * @return the value of yl_m_caseinfo.SuffererName
     *
     * @mbg.generated
     */
    public String getSufferername() {
        return sufferername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.SuffererName
     *
     * @param sufferername the value for yl_m_caseinfo.SuffererName
     *
     * @mbg.generated
     */
    public void setSufferername(String sufferername) {
        this.sufferername = sufferername == null ? null : sufferername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.SuffererGender
     *
     * @return the value of yl_m_caseinfo.SuffererGender
     *
     * @mbg.generated
     */
    public String getSufferergender() {
        return sufferergender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.SuffererGender
     *
     * @param sufferergender the value for yl_m_caseinfo.SuffererGender
     *
     * @mbg.generated
     */
    public void setSufferergender(String sufferergender) {
        this.sufferergender = sufferergender == null ? null : sufferergender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.SuffererInfo
     *
     * @return the value of yl_m_caseinfo.SuffererInfo
     *
     * @mbg.generated
     */
    public String getSuffererinfo() {
        return suffererinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.SuffererInfo
     *
     * @param suffererinfo the value for yl_m_caseinfo.SuffererInfo
     *
     * @mbg.generated
     */
    public void setSuffererinfo(String suffererinfo) {
        this.suffererinfo = suffererinfo == null ? null : suffererinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CrimeOpportunity
     *
     * @return the value of yl_m_caseinfo.CrimeOpportunity
     *
     * @mbg.generated
     */
    public String getCrimeopportunity() {
        return crimeopportunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CrimeOpportunity
     *
     * @param crimeopportunity the value for yl_m_caseinfo.CrimeOpportunity
     *
     * @mbg.generated
     */
    public void setCrimeopportunity(String crimeopportunity) {
        this.crimeopportunity = crimeopportunity == null ? null : crimeopportunity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CrimeImporExport
     *
     * @return the value of yl_m_caseinfo.CrimeImporExport
     *
     * @mbg.generated
     */
    public String getCrimeimporexport() {
        return crimeimporexport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CrimeImporExport
     *
     * @param crimeimporexport the value for yl_m_caseinfo.CrimeImporExport
     *
     * @mbg.generated
     */
    public void setCrimeimporexport(String crimeimporexport) {
        this.crimeimporexport = crimeimporexport == null ? null : crimeimporexport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CrimeFeature
     *
     * @return the value of yl_m_caseinfo.CrimeFeature
     *
     * @mbg.generated
     */
    public String getCrimefeature() {
        return crimefeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CrimeFeature
     *
     * @param crimefeature the value for yl_m_caseinfo.CrimeFeature
     *
     * @mbg.generated
     */
    public void setCrimefeature(String crimefeature) {
        this.crimefeature = crimefeature == null ? null : crimefeature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CrimeTools
     *
     * @return the value of yl_m_caseinfo.CrimeTools
     *
     * @mbg.generated
     */
    public String getCrimetools() {
        return crimetools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CrimeTools
     *
     * @param crimetools the value for yl_m_caseinfo.CrimeTools
     *
     * @mbg.generated
     */
    public void setCrimetools(String crimetools) {
        this.crimetools = crimetools == null ? null : crimetools.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CrimeImplement
     *
     * @return the value of yl_m_caseinfo.CrimeImplement
     *
     * @mbg.generated
     */
    public String getCrimeimplement() {
        return crimeimplement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CrimeImplement
     *
     * @param crimeimplement the value for yl_m_caseinfo.CrimeImplement
     *
     * @mbg.generated
     */
    public void setCrimeimplement(String crimeimplement) {
        this.crimeimplement = crimeimplement == null ? null : crimeimplement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.SelectionPlace
     *
     * @return the value of yl_m_caseinfo.SelectionPlace
     *
     * @mbg.generated
     */
    public String getSelectionplace() {
        return selectionplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.SelectionPlace
     *
     * @param selectionplace the value for yl_m_caseinfo.SelectionPlace
     *
     * @mbg.generated
     */
    public void setSelectionplace(String selectionplace) {
        this.selectionplace = selectionplace == null ? null : selectionplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CrimeMotive
     *
     * @return the value of yl_m_caseinfo.CrimeMotive
     *
     * @mbg.generated
     */
    public String getCrimemotive() {
        return crimemotive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CrimeMotive
     *
     * @param crimemotive the value for yl_m_caseinfo.CrimeMotive
     *
     * @mbg.generated
     */
    public void setCrimemotive(String crimemotive) {
        this.crimemotive = crimemotive == null ? null : crimemotive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CaseKeywords
     *
     * @return the value of yl_m_caseinfo.CaseKeywords
     *
     * @mbg.generated
     */
    public String getCasekeywords() {
        return casekeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CaseKeywords
     *
     * @param casekeywords the value for yl_m_caseinfo.CaseKeywords
     *
     * @mbg.generated
     */
    public void setCasekeywords(String casekeywords) {
        this.casekeywords = casekeywords == null ? null : casekeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.LossPossession
     *
     * @return the value of yl_m_caseinfo.LossPossession
     *
     * @mbg.generated
     */
    public String getLosspossession() {
        return losspossession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.LossPossession
     *
     * @param losspossession the value for yl_m_caseinfo.LossPossession
     *
     * @mbg.generated
     */
    public void setLosspossession(String losspossession) {
        this.losspossession = losspossession == null ? null : losspossession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.InvestigationDesc
     *
     * @return the value of yl_m_caseinfo.InvestigationDesc
     *
     * @mbg.generated
     */
    public String getInvestigationdesc() {
        return investigationdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.InvestigationDesc
     *
     * @param investigationdesc the value for yl_m_caseinfo.InvestigationDesc
     *
     * @mbg.generated
     */
    public void setInvestigationdesc(String investigationdesc) {
        this.investigationdesc = investigationdesc == null ? null : investigationdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yl_m_caseinfo.CaseDownloadNumber
     *
     * @return the value of yl_m_caseinfo.CaseDownloadNumber
     *
     * @mbg.generated
     */
    public Integer getCasedownloadnumber() {
        return casedownloadnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yl_m_caseinfo.CaseDownloadNumber
     *
     * @param casedownloadnumber the value for yl_m_caseinfo.CaseDownloadNumber
     *
     * @mbg.generated
     */
    public void setCasedownloadnumber(Integer casedownloadnumber) {
        this.casedownloadnumber = casedownloadnumber;
    }
}