package com.ssm.kernel.dao;

import com.ssm.kernel.model.CaseType;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CaseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_type
     *
     * @mbg.generated
     */
    @Delete({
        "delete from case_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_type
     *
     * @mbg.generated
     */
    @Insert({
        "insert into case_type (id, case_type_no, ",
        "case_type_name, parent_id, ",
        "description, create_user_id, ",
        "create_user_name, create_time, ",
        "update_user_id, update_user_name, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{caseTypeNo,jdbcType=VARCHAR}, ",
        "#{caseTypeName,jdbcType=VARCHAR}, #{parentId,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR}, #{createUserId,jdbcType=INTEGER}, ",
        "#{createUserName,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateUserId,jdbcType=INTEGER}, #{updateUserName,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(CaseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_type
     *
     * @mbg.generated
     */
    int insertSelective(CaseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_type
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, case_type_no, case_type_name, parent_id, description, create_user_id, create_user_name, ",
        "create_time, update_user_id, update_user_name, update_time",
        "from case_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.ssm.kernel.dao.CaseTypeMapper.BaseResultMap")
    CaseType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CaseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_type
     *
     * @mbg.generated
     */
    @Update({
        "update case_type",
        "set case_type_no = #{caseTypeNo,jdbcType=VARCHAR},",
          "case_type_name = #{caseTypeName,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=INTEGER},",
          "description = #{description,jdbcType=VARCHAR},",
          "create_user_id = #{createUserId,jdbcType=INTEGER},",
          "create_user_name = #{createUserName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_user_id = #{updateUserId,jdbcType=INTEGER},",
          "update_user_name = #{updateUserName,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CaseType record);
}