package com.ssm.kernel.dao;

import com.ssm.kernel.model.YLMCaseInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface YLMCaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yl_m_caseinfo
     *
     * @mbg.generated
     */
    @Delete({
        "delete from yl_m_caseinfo",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yl_m_caseinfo
     *
     * @mbg.generated
     */
    @Insert({
        "insert into yl_m_caseinfo (ID, CaseNo, ",
        "CaseName, RegisterTime, ",
        "ReportTime, BreakTime, ",
        "WithdrawTime, FindTime, ",
        "FindAddressName, CaseTypeID, ",
        "CaseLevel, StartTime, ",
        "EndTime, AddressName, ",
        "AddressLogitude, AddressLatitude, ",
        "IsRegister, Property, ",
        "CaseStatus, Description, ",
        "SuspectNumber, HandleOfficeID, ",
        "HandleUsers, ReportPerson, ",
        "ReportPhone, AreaOffice, ",
        "IllegalPersonExists, CreateOfficeID, ",
        "IsMurderCase, SiteSurveyNo, ",
        "HandleCaseNo, PoliceComprehensiveNo, ",
        "SceneInquestNo, ReceivingAlarmNo, ",
        "IntelligenceCaseNo, SuffererName, ",
        "SuffererGender, SuffererInfo, ",
        "CrimeOpportunity, CrimeImporExport, ",
        "CrimeFeature, CrimeTools, ",
        "CrimeImplement, SelectionPlace, ",
        "CrimeMotive, CaseKeywords, ",
        "LossPossession, InvestigationDesc, ",
        "CaseDownloadNumber)",
        "values (#{id,jdbcType=INTEGER}, #{caseno,jdbcType=VARCHAR}, ",
        "#{casename,jdbcType=VARCHAR}, #{registertime,jdbcType=TIMESTAMP}, ",
        "#{reporttime,jdbcType=TIMESTAMP}, #{breaktime,jdbcType=TIMESTAMP}, ",
        "#{withdrawtime,jdbcType=TIMESTAMP}, #{findtime,jdbcType=TIMESTAMP}, ",
        "#{findaddressname,jdbcType=VARCHAR}, #{casetypeid,jdbcType=INTEGER}, ",
        "#{caselevel,jdbcType=INTEGER}, #{starttime,jdbcType=TIMESTAMP}, ",
        "#{endtime,jdbcType=TIMESTAMP}, #{addressname,jdbcType=VARCHAR}, ",
        "#{addresslogitude,jdbcType=REAL}, #{addresslatitude,jdbcType=REAL}, ",
        "#{isregister,jdbcType=VARCHAR}, #{property,jdbcType=VARCHAR}, ",
        "#{casestatus,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{suspectnumber,jdbcType=INTEGER}, #{handleofficeid,jdbcType=INTEGER}, ",
        "#{handleusers,jdbcType=VARCHAR}, #{reportperson,jdbcType=VARCHAR}, ",
        "#{reportphone,jdbcType=VARCHAR}, #{areaoffice,jdbcType=VARCHAR}, ",
        "#{illegalpersonexists,jdbcType=VARCHAR}, #{createofficeid,jdbcType=VARCHAR}, ",
        "#{ismurdercase,jdbcType=VARCHAR}, #{sitesurveyno,jdbcType=VARCHAR}, ",
        "#{handlecaseno,jdbcType=VARCHAR}, #{policecomprehensiveno,jdbcType=VARCHAR}, ",
        "#{sceneinquestno,jdbcType=VARCHAR}, #{receivingalarmno,jdbcType=VARCHAR}, ",
        "#{intelligencecaseno,jdbcType=VARCHAR}, #{sufferername,jdbcType=VARCHAR}, ",
        "#{sufferergender,jdbcType=VARCHAR}, #{suffererinfo,jdbcType=VARCHAR}, ",
        "#{crimeopportunity,jdbcType=VARCHAR}, #{crimeimporexport,jdbcType=VARCHAR}, ",
        "#{crimefeature,jdbcType=VARCHAR}, #{crimetools,jdbcType=VARCHAR}, ",
        "#{crimeimplement,jdbcType=VARCHAR}, #{selectionplace,jdbcType=VARCHAR}, ",
        "#{crimemotive,jdbcType=VARCHAR}, #{casekeywords,jdbcType=VARCHAR}, ",
        "#{losspossession,jdbcType=VARCHAR}, #{investigationdesc,jdbcType=VARCHAR}, ",
        "#{casedownloadnumber,jdbcType=INTEGER})"
    })
    int insert(YLMCaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yl_m_caseinfo
     *
     * @mbg.generated
     */
    int insertSelective(YLMCaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yl_m_caseinfo
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, CaseNo, CaseName, RegisterTime, ReportTime, BreakTime, WithdrawTime, FindTime, ",
        "FindAddressName, CaseTypeID, CaseLevel, StartTime, EndTime, AddressName, AddressLogitude, ",
        "AddressLatitude, IsRegister, Property, CaseStatus, Description, SuspectNumber, ",
        "HandleOfficeID, HandleUsers, ReportPerson, ReportPhone, AreaOffice, IllegalPersonExists, ",
        "CreateOfficeID, IsMurderCase, SiteSurveyNo, HandleCaseNo, PoliceComprehensiveNo, ",
        "SceneInquestNo, ReceivingAlarmNo, IntelligenceCaseNo, SuffererName, SuffererGender, ",
        "SuffererInfo, CrimeOpportunity, CrimeImporExport, CrimeFeature, CrimeTools, ",
        "CrimeImplement, SelectionPlace, CrimeMotive, CaseKeywords, LossPossession, InvestigationDesc, ",
        "CaseDownloadNumber",
        "from yl_m_caseinfo",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.ssm.kernel.dao.YLMCaseInfoMapper.BaseResultMap")
    YLMCaseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yl_m_caseinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YLMCaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yl_m_caseinfo
     *
     * @mbg.generated
     */
    @Update({
        "update yl_m_caseinfo",
        "set CaseNo = #{caseno,jdbcType=VARCHAR},",
          "CaseName = #{casename,jdbcType=VARCHAR},",
          "RegisterTime = #{registertime,jdbcType=TIMESTAMP},",
          "ReportTime = #{reporttime,jdbcType=TIMESTAMP},",
          "BreakTime = #{breaktime,jdbcType=TIMESTAMP},",
          "WithdrawTime = #{withdrawtime,jdbcType=TIMESTAMP},",
          "FindTime = #{findtime,jdbcType=TIMESTAMP},",
          "FindAddressName = #{findaddressname,jdbcType=VARCHAR},",
          "CaseTypeID = #{casetypeid,jdbcType=INTEGER},",
          "CaseLevel = #{caselevel,jdbcType=INTEGER},",
          "StartTime = #{starttime,jdbcType=TIMESTAMP},",
          "EndTime = #{endtime,jdbcType=TIMESTAMP},",
          "AddressName = #{addressname,jdbcType=VARCHAR},",
          "AddressLogitude = #{addresslogitude,jdbcType=REAL},",
          "AddressLatitude = #{addresslatitude,jdbcType=REAL},",
          "IsRegister = #{isregister,jdbcType=VARCHAR},",
          "Property = #{property,jdbcType=VARCHAR},",
          "CaseStatus = #{casestatus,jdbcType=VARCHAR},",
          "Description = #{description,jdbcType=VARCHAR},",
          "SuspectNumber = #{suspectnumber,jdbcType=INTEGER},",
          "HandleOfficeID = #{handleofficeid,jdbcType=INTEGER},",
          "HandleUsers = #{handleusers,jdbcType=VARCHAR},",
          "ReportPerson = #{reportperson,jdbcType=VARCHAR},",
          "ReportPhone = #{reportphone,jdbcType=VARCHAR},",
          "AreaOffice = #{areaoffice,jdbcType=VARCHAR},",
          "IllegalPersonExists = #{illegalpersonexists,jdbcType=VARCHAR},",
          "CreateOfficeID = #{createofficeid,jdbcType=VARCHAR},",
          "IsMurderCase = #{ismurdercase,jdbcType=VARCHAR},",
          "SiteSurveyNo = #{sitesurveyno,jdbcType=VARCHAR},",
          "HandleCaseNo = #{handlecaseno,jdbcType=VARCHAR},",
          "PoliceComprehensiveNo = #{policecomprehensiveno,jdbcType=VARCHAR},",
          "SceneInquestNo = #{sceneinquestno,jdbcType=VARCHAR},",
          "ReceivingAlarmNo = #{receivingalarmno,jdbcType=VARCHAR},",
          "IntelligenceCaseNo = #{intelligencecaseno,jdbcType=VARCHAR},",
          "SuffererName = #{sufferername,jdbcType=VARCHAR},",
          "SuffererGender = #{sufferergender,jdbcType=VARCHAR},",
          "SuffererInfo = #{suffererinfo,jdbcType=VARCHAR},",
          "CrimeOpportunity = #{crimeopportunity,jdbcType=VARCHAR},",
          "CrimeImporExport = #{crimeimporexport,jdbcType=VARCHAR},",
          "CrimeFeature = #{crimefeature,jdbcType=VARCHAR},",
          "CrimeTools = #{crimetools,jdbcType=VARCHAR},",
          "CrimeImplement = #{crimeimplement,jdbcType=VARCHAR},",
          "SelectionPlace = #{selectionplace,jdbcType=VARCHAR},",
          "CrimeMotive = #{crimemotive,jdbcType=VARCHAR},",
          "CaseKeywords = #{casekeywords,jdbcType=VARCHAR},",
          "LossPossession = #{losspossession,jdbcType=VARCHAR},",
          "InvestigationDesc = #{investigationdesc,jdbcType=VARCHAR},",
          "CaseDownloadNumber = #{casedownloadnumber,jdbcType=INTEGER}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(YLMCaseInfo record);
}